services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # Puerto para conectar a Mongo
    volumes:
      - mongo-data:/data/db # Persistencia de datos
    networks:
      - red-integrador

  frontend:
    build:
      context: ./TP5-DiazMarcos-Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80" # Exponer Apache en el puerto 8080
    depends_on:
      - backend # El frontend depende del backend
    environment:
      - BACKEND_URL=http://localhost:4000 # Backend URL interno en la red
    networks:
      - red-integrador

  backend:
    build:
      context: ./TP5-DiazMarcos-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000" # Exponer el backend en el puerto 3000
    depends_on:
      - mongo # Asegura que MongoDB esté listo antes del backend
    networks:
      - red-integrador
    volumes:
      - ./.env:/app/.env

networks:
  red-integrador:
    driver: bridge

volumes:
  mongo-data:
