name: CI/CD Pipeline

# 1. Ejecutar el workflow en cada push a la rama master.
on:
  push:
    branches:
      - master

jobs:
  # Job para construir y publicar imágenes Docker.
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir imagen para el Frontend
      - name: Build Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./TP5-DiazMarcos-Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
